//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBMDBEntities : DbContext
    {
        public SBMDBEntities()
            : base("name=SBMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<ApplicationType> ApplicationTypes { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<BeneficiayAidStatu> BeneficiayAidStatus { get; set; }
        public virtual DbSet<BranchLocation> BranchLocations { get; set; }
        public virtual DbSet<CharitableFundType> CharitableFundTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CollegeType> CollegeTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DistitutionType> DistitutionTypes { get; set; }
        public virtual DbSet<EducationLevel> EducationLevels { get; set; }
        public virtual DbSet<EducationType> EducationTypes { get; set; }
        public virtual DbSet<EmailSetting> EmailSettings { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<HouseType> HouseTypes { get; set; }
        public virtual DbSet<IdProofType> IdProofTypes { get; set; }
        public virtual DbSet<InvertType> InvertTypes { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<ReligiousFundType> ReligiousFundTypes { get; set; }
        public virtual DbSet<ResidentType> ResidentTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleAssignment> RoleAssignments { get; set; }
        public virtual DbSet<SchoolClassLevel> SchoolClassLevels { get; set; }
        public virtual DbSet<SchoolType> SchoolTypes { get; set; }
        public virtual DbSet<SMSSetting> SMSSettings { get; set; }
        public virtual DbSet<SMSTemplate> SMSTemplates { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SurveyAreaCode> SurveyAreaCodes { get; set; }
        public virtual DbSet<SurveyConclusionCategory> SurveyConclusionCategories { get; set; }
        public virtual DbSet<SurveyConcusionQuestion> SurveyConcusionQuestions { get; set; }
        public virtual DbSet<SurveyStatu> SurveyStatus { get; set; }
        public virtual DbSet<SurveyType> SurveyTypes { get; set; }
        public virtual DbSet<ToiletType> ToiletTypes { get; set; }
        public virtual DbSet<TrustType> TrustTypes { get; set; }
        public virtual DbSet<UniversityType> UniversityTypes { get; set; }
        public virtual DbSet<WaterConnection> WaterConnections { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
        public virtual DbSet<CollegeDegreeLevel> CollegeDegreeLevels { get; set; }
        public virtual DbSet<GasCompany> GasCompanies { get; set; }
        public virtual DbSet<PensionType> PensionTypes { get; set; }
    }
}
